version: "3.9"

services:
  loglumen-server:
    container_name: loglumen-server
    build:
      context: ../../server
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      LOGLUMEN_BIND_ADDRESS: 0.0.0.0:8080
    volumes:
      - ../../config/server.toml:/config/server.toml:ro
    restart: unless-stopped
